# Generated by Django 5.0 on 2023-12-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('from_points', models.PositiveIntegerField()),
                ('to_points', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='rankings_images/')),
            ],
        ),
    ]
