# Generated by Django 5.0 on 2023-12-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='level',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
