# Generated by Django 5.0 on 2023-12-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='redemption_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
