# Generated by Django 5.0 on 2024-05-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_code_random_code_remove_code_redemption_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('name_ima_before', models.CharField(max_length=255)),
                ('name_ima_after', models.CharField(max_length=255)),
                ('mode', models.IntegerField()),
                ('folder', models.CharField(max_length=255)),
                ('res', models.IntegerField()),
                ('rec', models.IntegerField()),
                ('ecological_point', models.CharField(max_length=255)),
                ('model_version', models.CharField(max_length=255)),
                ('success', models.IntegerField()),
            ],
        ),
    ]
