name: Docker Image CI

on:
  workflow_run:
    workflows: ["Unit Tests"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v4
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKER_PASS: ${{secrets.DOCKERHUB_PASS}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg API_KEY=${{ secrets.API_KEY }} --build-arg IP_SERVER=${{ secrets.IP_SERVER }} --build-arg CRYPTO_KEY=${{ secrets.CRYPTO_KEY }} --build-arg EMAIL_HOST_USER=${{ secrets.EMAIL_HOST_USER }} --build-arg EMAIL_HOST_PASSWORD=${{ secrets.EMAIL_HOST_PASSWORD }} --tag danielgara/sasvar:latest
      
    - name: Docker Push
      run: docker push danielgara/sasvar

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
      - run: exit 1